"""PITMuS -- reconstruct PIT bytecode mutations as Java source.

The reconstruction engine (:mod:`shared.mutate`) is imported by both CLI
front-ends in ``PITMuS/`` so they can never drift apart:

    python PITMuS/gen_dataset.py <system_path>    # -> dataset CSVs
    python PITMuS/inject.py      <system_path>    # -> mutant .java files

Typical library use::

    from shared import apply_mutation_with_fallback, load_source
    lines, tokens, spans = load_source("Foo.java")
    start, end, text = apply_mutation_with_fallback(lines, tokens, 42,
                                                   "negated conditional", 0)
"""

from .mutate import (          # explicit, so the _private helpers re-export too
    COND_BOUNDARY_OPCODES,
    COND_OPCODES,
    INVOKE_OPCODES,
    MATH_OPCODES,
    RETURN_OPCODES,
    _AdjTok,
    _OPERAND_STOP,
    _RELOPS,
    _SWITCH_LABEL_RE,
    _SWITCH_TERM_RE,
    _branch_cond_span,
    _cond_expr_start,
    _expr_end_col,
    _expr_start_col,
    _find_any_method_calls,
    _find_bool_assignment_rhs,
    _find_brace_open_before,
    _find_bytecode_switch,
    _find_call_span,
    _find_compound_bool_subexprs,
    _find_eq_method_calls,
    _find_instanceof_spans,
    _find_method_end,
    _find_switch_block,
    _first_body_line,
    _for_cond_range,
    _generic_bracket_indices,
    _hoist_sideeffect_cond,
    _is_concat_plus,
    _is_leaf_bool,
    _leading_cond_paren_span,
    _line_for_offset,
    _mutation_sort_key,
    _operand_left_start,
    _operand_right_end,
    _parse_switch_segments,
    _range_has_toplevel,
    _switch_body_terminated,
    _switch_scan_braces,
    _toplevel_semicolon,
    _type_end_col,
    apply_mutation,
    apply_mutation_multiline,
    apply_mutation_with_fallback,
    extract_javadoc,
    int_locals_in_span,
    extract_method_spans,
    extract_test_files,
    find_span_for_line,
    find_statement_span,
    load_source,
    load_switch_tables,
    nth_gt_run,
    nth_token,
    nth_token_in,
    parse_switch_tables,
    reconstruct_switch_default,
    replace_at,
    tokens_on_line,
)
from .version import dataset_dirname   # noqa: F401

__all__ = [
    "COND_BOUNDARY_OPCODES",
    "COND_OPCODES",
    "INVOKE_OPCODES",
    "MATH_OPCODES",
    "RETURN_OPCODES",
    "_AdjTok",
    "_OPERAND_STOP",
    "_RELOPS",
    "_SWITCH_LABEL_RE",
    "_SWITCH_TERM_RE",
    "_branch_cond_span",
    "_cond_expr_start",
    "_expr_end_col",
    "_expr_start_col",
    "_find_any_method_calls",
    "_find_bool_assignment_rhs",
    "_find_brace_open_before",
    "_find_bytecode_switch",
    "_find_call_span",
    "_find_compound_bool_subexprs",
    "_find_eq_method_calls",
    "_find_instanceof_spans",
    "_find_method_end",
    "_find_switch_block",
    "_first_body_line",
    "_for_cond_range",
    "_generic_bracket_indices",
    "_hoist_sideeffect_cond",
    "_is_concat_plus",
    "_is_leaf_bool",
    "_leading_cond_paren_span",
    "_line_for_offset",
    "_mutation_sort_key",
    "_operand_left_start",
    "_operand_right_end",
    "_parse_switch_segments",
    "_range_has_toplevel",
    "_switch_body_terminated",
    "_switch_scan_braces",
    "_toplevel_semicolon",
    "_type_end_col",
    "apply_mutation",
    "apply_mutation_multiline",
    "apply_mutation_with_fallback",
    "extract_javadoc",
    "int_locals_in_span",
    "extract_method_spans",
    "extract_test_files",
    "find_span_for_line",
    "find_statement_span",
    "load_source",
    "load_switch_tables",
    "nth_gt_run",
    "nth_token",
    "nth_token_in",
    "parse_switch_tables",
    "reconstruct_switch_default",
    "replace_at",
    "tokens_on_line",
    "dataset_dirname",
]
